FROM ubuntu:latest
MAINTAINER "granatumx" granatumx@github.com

ENV TERM=xterm-256color
ENV PATH="$PATH:."

ENV DEBIAN_FRONTEND noninteractive
ENV TZ America/New_York

RUN apt-get update
RUN apt-get install -y apt-utils

RUN mkdir -p /usr/src/gx
WORKDIR /usr/src/gx

# Just need jsonschemas and binary for installation
COPY jsonSchemas ./jsonSchemas
COPY installGbox .

ARG DATABASE_URL=postgres://postgres:12qw@192.168.1.101:5432/granatum
ENV DATABASE_URL=$DATABASE_URL
